image: gradle:7.4-jdk-11-alpine

stages:
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

Deploy_master:
  stage: deploy
  only:
    - master
  image: ruby:latest
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku
      --app=$HEROKU_APP_NAME
      --api-key=$HEROKU_API_KEY
    - export HEROKU_API_KEY=$HEROKU_API_KEY
    - heroku run --app $HEROKU_APP_NAME migrate
